#!/bin/sh

xrandr --output HDMI-0 --mode 1920x1080 --rate 144.00
sh ~/.local/scripts/mouse.sh
xwallpaper --zoom ~/.config/xwallpaper/wallpaper
xrdb ~/.Xresources
picom --fade-in-step=1 --fade-out-step=1 --fade-delta=0 -b
pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
polybar &
emacs --daemon

pgrep bspswallow || bspswallow &

bspc rule -r "*"

#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d         

bspc config border_width         2
#bspc config focused_border_color \#00308F

bspc config window_gap          12
bspc config top_padding		30
bspc config borderless_monocle true
bspc config gapless_monocle true
#bspc config right_monocle_padding 0
#bspc config left_monocle_padding 0
#bspc config bottom_monocle_padding 0
#bspc config top_monocle_padding 0

bspc config single_monocle true

bspc rule -a '*' state=tiled

bspc rule -a '*:*:Picture-in-Picture' state=floating rectangle=597x336+1130+200 sticky=on

bspc rule -a '*:*:calculator' state=floating rectangle=800x600 center=on
